name: "quiz_app"

services:
  flask:
    build:
      context: back-end
      dockerfile: ./docker/dev.Dockerfile
    ports:
      - 8000:8000
    container_name: "quiz_app_backend"
  react:
    build:
      context: front-end
      dockerfile: ./docker/dev.Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - flask
    container_name: "quiz_app_frontend"